require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityKeepAwake', :path => '../../node_modules/@capacitor-community/keep-awake'
  pod 'CapacitorFirebaseAuthentication', :path => '../../node_modules/@capacitor-firebase/authentication'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/@revenuecat/purchases-capacitor'
end

target 'App' do
  capacitor_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
  end
  assertDeploymentTarget(installer)

  # إصلاح خطأ RecaptchaInterop: double-quoted includes في framework headers
  recaptcha_headers = [
    'Pods/RecaptchaInterop/RecaptchaEnterprise/RecaptchaInterop/Public/RecaptchaInterop/RCARecaptchaClientProtocol.h',
    'Pods/RecaptchaInterop/RecaptchaEnterprise/RecaptchaInterop/Public/RecaptchaInterop/RCARecaptchaProtocol.h',
    'Pods/RecaptchaInterop/RecaptchaEnterprise/RecaptchaInterop/Public/RecaptchaInterop/RecaptchaInterop.h',
    'Pods/Target Support Files/RecaptchaInterop/RecaptchaInterop-umbrella.h',
  ]
  recaptcha_headers.each do |header_path|
    full_path = File.join(File.dirname(__FILE__), header_path)
    next unless File.exist?(full_path)
    content = File.read(full_path)
    updated = content.gsub(/#import "RCAActionProtocol\.h"/, '#import <RecaptchaInterop/RCAActionProtocol.h>')
                     .gsub(/#import "RCARecaptchaClientProtocol\.h"/, '#import <RecaptchaInterop/RCARecaptchaClientProtocol.h>')
                     .gsub(/#import "RCARecaptchaProtocol\.h"/, '#import <RecaptchaInterop/RCARecaptchaProtocol.h>')
                     .gsub(/#import "RecaptchaInterop\.h"/, '#import <RecaptchaInterop/RecaptchaInterop.h>')
    File.write(full_path, updated) if updated != content
  end
end
